<?php 


$this->document->setProperty("leftNavHide","bool",true);
$this->layout()->setLayout("layout-ft"); 


$relatedProducts = $this->product->getRelated("relatedProducts");

$associatedArticles = $this->product->getRelated("associatedArticles");
$relatedAccessories = $this->product->getRelated("relatedAccessories");
$caracteristiques = $this->product->getCharacteristicsFo();
$extras = $this->product->getRelated("extras");

$childrens = $this->product->getChilds();
$lesplus = $this->product->getLesPlusArray();


/**** CARACTERISTIQUES ***/

 $hasMarquageCe = false;
 $hasDonneesTech = false;
 $hasDescription= false;
 $caracteristiques =  $this->product->getCharacteristicsArray();
 $htmlStd='';
 $htmlStd .= '<dl class="dl-horizontal">';
 $htmlCe = $htmlDonneeTech = $htmlDescription = $htmlStd;
 $logoAssets = array();
 foreach ($caracteristiques as $key => $value) {

 			if(!is_array($value) || !isset($value["content"]) || strlen(trim($value["content"]))==0) {
 				continue;
 			}
 		
			$content = trim($value["content"]);
			$htmlSingle = "";

			if(!isset($value["label"]) || strlen($content)==0)
				continue;

			$isHidden = isset($value["is_hidden"]) && $value["is_hidden"];

			$htmlSingle.= '<dt class=""'.($isHidden?' style="display:none"':'').'>';
			$htmlSingle.= strlen($value["label"])>0?ucfirst(trim($value["label"])):"";
			$htmlSingle.= '</dt>';
			$htmlSingle.= '<dd class=""'.($isHidden?' style="display:none"':'').'>';
			

			if(isset($value["description"])) {
				//$html.= '<br />';
				$htmlSingle.= ucfirst(trim($value["description"]));

			}
			else {
				$htmlSingle.= ucfirst($content);
			}

			$htmlSingle.= '</dd>';


			if(isset($value["logo"])) {
				$logoAssets[] = $value["logo"];
			}

			if(isset($value["isMarquageCe"]) && $value["isMarquageCe"]) {
				$hasMarquageCe = true;

				$htmlCe .=$htmlSingle;
			}
			else if(isset($value["isDonneeTechnique"]) && $value["isDonneeTechnique"]) {
				$hasDonneesTech = true;

				$htmlDonneeTech.=$htmlSingle;
			}
			else if(isset($value["isDescription"]) && $value["isDescription"]) {
				$hasDescription = true;

				$htmlDescription .=$htmlSingle;
			}

			else
				$htmlStd .=$htmlSingle;

			
			//$html.="</li>\n";
}
$htmlStd .='</dl>';
$htmlCe .='</dl>';
$htmlDescription .='</dl>';
$htmlDonneeTech .='</dl>';


?>



<!-- MAIN LAYOUT -->
<div class="row">

<!-- First col -->
<div class="ft-col-1">



<!-- pas de row & col, sinon les SVG ne s'affichent pas -->
<div class="">
	
	<div class="">
		 <div class="page-header">

		 	<div id="logo2" style='width:338px;height:30px'>

		 	<!--<img width="462" height="41" src="http://pimcore.florent.local/website/static_lpn/img/logo_lpn.gif" />
		 	<img width="462" height="41" src="http://pimcore.florent.local/website/static_lpn/img/logo_lpn.png" />-->
		 	<!-- Generated by IcoMoon.io -->
<svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="338" height="30" viewBox="0 0 11539 1024">
<title></title>
<g id="icomoon-ignore">
</g>
<path fill="#000" d="M734.383 346.187l-111.166 260.271h219.76l-108.594-260.271z"></path>
<path fill="#000" d="M173.231 208.272h72.379v582.656h179.3v67.209h-251.679v-649.865zM736.106 177.252l292.19 680.885h-80.172l-76.7-184.445h-277.529l-78.423 184.445h-79.298l299.932-680.885zM0 1024h1147.554v-1023.925h-1147.554v1023.925z"></path>
<path fill="#000" d="M2727.986 392.741c0-106.871-78.423-117.236-165.463-117.236h-21.554v233.572h22.428c81.87 0 164.589-15.51 164.589-116.336z"></path>
<path fill="#000" d="M2103.87 346.187l-111.166 260.271h219.76l-108.594-260.271z"></path>
<path fill="#000" d="M5854.708 392.741c0-106.871-78.423-117.236-165.488-117.236h-21.579v233.572h22.453c81.87 0 164.614-15.51 164.614-116.336z"></path>
<path fill="#000" d="M3241.784 802.117c48.253 0 105.147-18.107 144.784-48.253l-156.847-157.721h94.807l112.041 117.186c48.278-50.85 71.53-110.317 71.53-180.099 0-148.28-117.211-268.912-266.315-268.912s-266.315 121.506-266.315 268.912c0 146.507 118.934 268.887 266.315 268.887z"></path>
<path fill="#000" d="M1769.397 389.27c0-105.996-85.342-113.764-169.784-113.764h-26.724v230.999h48.253c80.172 0 148.255-24.151 148.255-117.236z"></path>
<path fill="#000" d="M1500.485 208.272h106.846c56.045 0 113.789 1.748 161.193 34.491 48.278 33.617 73.278 90.487 73.278 148.255 0 52.549-21.579 105.996-62.064 139.639-43.957 36.165-99.977 43.058-154.299 43.058h-52.549v284.422h-72.404v-649.865zM2397.758 858.137h-80.147l-76.7-184.445h-277.529l-78.423 184.445h-79.298l299.932-680.885 292.165 680.885zM2468.589 208.272h93.933c123.255 0 237.868 32.768 237.868 179.275 0 99.977-62.914 170.658-162.891 179.275l206.848 291.316h-88.763l-196.508-285.271h-18.107v285.271h-72.379v-649.865zM3241.784 197.083c187.892 0 338.719 152.551 338.719 338.744 0 90.487-32.768 163.715-93.958 229.201l97.405 99.153h-92.21l-54.322-58.618c-53.423 40.51-130.148 63.788-195.634 63.788-185.319 0-338.719-148.255-338.719-335.273 0-186.168 153.4-336.996 338.719-336.996zM3677.184 208.272h72.404v386.997c0 48.278-1.723 103.424 28.447 144.784 28.447 39.636 83.593 62.064 130.997 62.064 46.555 0 97.38-21.554 127.575-57.744 34.466-41.385 31.894-98.229 31.894-149.104v-386.997h72.379v406.803c0 70.706-5.17 126.726-56.869 180.124-44.806 48.278-109.468 74.153-174.979 74.153-61.19 0-124.104-23.277-168.061-66.36-56.894-54.297-63.788-113.789-63.788-187.916v-406.803zM4269.431 208.272h336.996v67.234h-264.592v193.036h256.824v67.284h-256.824v255.101h264.592v67.209h-336.996v-649.865zM4672.912 208.272h387.846v67.234h-158.62v582.631h-72.379v-582.631h-156.847v-67.234zM5134.91 208.272h337.021v67.234h-264.592v193.036h256.849v67.284h-256.849v255.101h264.592v67.209h-337.021v-649.865zM5595.286 208.272h93.933c123.305 0 237.868 32.768 237.868 179.275 0 99.977-62.864 170.658-162.891 179.275l206.848 291.316h-88.763l-196.508-285.271h-18.132v285.271h-72.354v-649.865zM6064.228 858.137v-649.865h72.429v649.865h-72.429zM6268.528 208.272h337.021v67.234h-264.567v193.036h256.824v67.284h-256.824v255.101h264.567v67.209h-337.021v-649.865zM1239.34 1024h5627.38v-1023.925h-5627.38v1023.925z"></path>
<path fill="#000" d="M8224.568 264.317c-149.104 0-266.315 121.506-266.315 268.912 0 146.507 118.934 268.887 266.315 268.887 147.356 0 266.29-122.38 266.29-268.887 0-147.406-117.186-268.912-266.29-268.912z"></path>
<path fill="#000" d="M11233.979 275.506h-264.592v193.036h256.849v67.284h-256.849v255.101h264.592v67.209h-336.946v-649.865h336.946v67.234zM10825.428 858.137h-251.679v-649.865h72.379v582.656h179.3v67.209zM10502.169 858.137h-251.679v-649.865h72.379v582.656h179.3v67.209zM10127.085 275.506h-264.592v193.036h256.874v67.284h-256.874v255.101h264.592v67.209h-336.971v-649.865h336.971v67.234zM9455.591 896.924l-263.717-688.652h78.448l185.269 495.566 185.319-495.566h78.423l-263.742 688.652zM9123.64 615.074c0 70.706-5.17 126.726-56.894 180.124-44.806 48.278-109.393 74.153-174.904 74.153-61.215 0-124.154-23.277-168.136-66.36-56.844-54.297-63.763-113.789-63.763-187.916v-406.803h72.429v386.997c0 48.278-1.748 103.424 28.397 144.784 28.472 39.636 83.593 62.064 131.072 62.064 46.53 0 97.38-21.554 127.525-57.744 34.491-41.385 31.869-98.229 31.869-149.104v-386.997h72.404v406.803zM8224.568 869.351c-185.319 0-338.719-148.255-338.719-335.273 0-186.168 153.4-336.996 338.719-336.996 185.269 0 338.719 150.828 338.719 336.996 0 187.017-153.45 335.273-338.719 335.273zM7783.099 887.433l-506.78-530.057v500.761h-72.404v-677.438l506.78 530.932v-503.358h72.404v679.162zM6958.48 1024h4574.907v-1023.925h-4574.907v1023.925z"></path>
</svg>

</div>

		       <!-- <h4><?php echo $this->product->getSubtype(); ?></h4>-->
		        <h1 style=""><?php echo $this->product->getMage_short_name(3000); ?></h1>
		        <?php
		        $subtitle = strlen($this->product->getSku())>0?$this->product->getSku():"";
		        if(strlen($this->product->name_scienergie_court)) {
		        	if(strlen($subtitle)>0) 
		        		$subtitle .=" - ";
		        	$subtitle .=$this->product->name_scienergie_court;
		        }
		        if (strlen($subtitle)>0) {
		        	echo $subtitle = '<p>'.$subtitle.'</p>';
		        }
		        ?>
		        <hr />
		        <h4>Fiche technique</h4>
		        <br />
		        <hr />

		        <?php
		        if(is_array($logoAssets) && count($logoAssets)>0) { ?>
		        	<?php
		        	foreach ($logoAssets as  $asset) {
		        		//echo '<div class="col-xs-2__">';
			        	echo  $asset->getThumbnail("magento_logo")->getHTML(array("class"=>'ft-logo')); 
			        	//echo '</div>';
			        }
			        ?>
			   	 
			      <?php 
		        }
		        
		        ?>
		        <hr />
		        <div class="row">
					

				    	
						
				        <?php for($i=1; $i<=3; $i++) { ?>
				            <?php
				            	try {
				                	$image = $this->product->{"getImage_" . $i}();
				            	}
				            	catch (\Exception $e) {
						            $image=null;
						        }	
				            ?>
				            <?php if($image instanceof Asset_Image) { 
				            	$src = "".$image->getThumbnail("galleryThumbnail");
				            	
				            	if(strstr($src,"pantone.gif"))
				            		continue;
				            	?>
				                <div class="col-xs-12">
				                    <a href="<?php echo $image->getThumbnail("galleryLightbox"); ?>" class="thumbnail">
				                        <img class="img-responsive" src="<?php echo $src; ?>">
				                    </a>
				                </div>
				            <?php } ?>
				        <?php } ?>

				</div>


		 </div>
	</div>
</div>


</div>
<!-- First col / -->
<!-- Second col -->
<div class="ft-col-2">


<div class="row">

	<div class="col-xs-12">
	
	     



<?php
if ($hasDescription) {
	echo "<h2>Description</h2>";
	echo $htmlDescription;
}

if ($hasDonneesTech) {
	echo "<h2>Données techniques</h2>";
	echo $htmlDonneeTech;
}

echo $htmlStd;


if ($hasMarquageCe) {
	echo "<h2>Déclaration de performance</h2>";
	echo $htmlCe;
	echo '<p class="small">Il n’existe pas de PV pour le classement au feu des parquets massifs et contrecollés. Les classements feu que nous indiquons sur nos fiches techniques et autres documents sont des classements dits « conventionnels », stipulés dans les DTU 51.11 (Pose flottante des parquets contrecollés) et 51.2 (Pose collée des parquets massifs) et selon la norme NF 14341+A1.</p>';
}
?>
		
	</div>

	
</div>
<hr />
<?php 
//detail taxo
$taxonomies = $this->product->getSelfAndChildrenTaxonomyObjects('support');
if(count($taxonomies) > 0) { ?>
<div class="row">

	<div class="col-xs-12">
	<h3>Support</h3>
	</div>
<?php
foreach ($taxonomies as $label => $taxonomie) {
	echo '<div class="col-xs-4">';
	echo '<p><strong>'.ucfirst(strtolower($taxonomie->getLabel())).'</strong></p>';
	echo "<p>".$taxonomie->getHelp().'</p>';
	echo '</div>';
}
?>

</div>
<?php } ?>
<hr />

<?php 
//detail taxo
$taxonomies = $this->product->getSelfAndChildrenTaxonomyObjects('choix');
if(count($taxonomies) > 0) { ?>
<div class="row">

	<div class="col-xs-12">
	<h3>Choix</h3>
	</div>
<?php
foreach ($taxonomies as $label => $taxonomie) {
	echo '<div class="col-xs-4">';
	echo '<p><strong>'.ucfirst(strtolower($taxonomie->getLabel())).'</strong></p>';
	echo "<p>".$taxonomie->getHelp().'</p>';
	echo '</div>';
}
?>

</div>
<?php } ?>

<hr />


<div class="row">
	<div class="col">
	    <div class="page-header">
	       

	   		 <?php
	   		 if(count($childrens)>0) {

	   		 	$fields["Choix"] = "getChoix";
	   		 	$fields["Surface"] = "getTraitement_surface";
	   		 	$fields["Finition"] = "getFinition";
	   		 	$fields["Support"] = "getSupport";
	   		 	if($this->product->isParquetContrecolle()) {
	   		 		$fields["CU"] = "getCoucheUsure";
	   		 	}
	   		 	$fields["Colisage"] = "getColisage";
	   		 	$fields["Dimensions"] = "getPimonly_dimensions";
	   		 	$fields["Utilisation"] = "getCalculatedClasseUtilisation";
	   		 	$fields["EAN"] = "getEan";
	   		 	$fields["Prix Public HT<br /> au ".date('d/m/Y')] = "getPrice_4";
	   		 	$fields["FT"] = "getPreviewLink";



			echo   '<table class="table table-striped">  <thead><tr>';
			foreach ($fields as $key => $value) {
				echo '<th>'.$key.'</th>';
			}
			echo '</tr></thead>';

  			$index = 1;
  			$productsToDisplay =array();
			foreach ($childrens as $subProduct) {

				//Configurables
				if($subProduct->getEan()=="") {
					$subProductChildrens = $subProduct->getChilds();
		
					
					foreach ($subProductChildrens as $subsubProduct) {
						$productsToDisplay[] = $subsubProduct;
					
					}

				}
				else { 
					$productsToDisplay[] = $subProduct;
					
				}
			}

			foreach ($productsToDisplay as $subproduct) {
				?>
					<tr>
						<?php
						foreach ($fields as $key => $value) {
							$v = $subproduct->$value();
							echo '<td>'.$v.'</td>';
						}
						?>
					     
					   
					    
					    </tr>


				<?php

			}
			echo   "</table>";
		}
		?>

	    </div>
	</div>

 <!-- Fin product header -->  


</div> <!-- row -->






<hr />

<?php if (strlen($this->product->getDescription())>0) : ?>
<div class="row">
	<h3 class="col-xs-12">Description</h3>
	<div class="caracteristiques col-8">
	<?php echo nl2br($this->product->getDescription()); ?>
	</div>
	<div class="caracteristiques col-4">
	<h3><!--Vous le choisirez pour: -->&nbsp;</h3>
	<?php echo nl2br($this->product->getMage_lesplus()); ?>
	</div>

</div>
<?php endif; ?>



	


<div  class="row">

     <?php
    if(count($extras)>0) {
    	echo "<div class='col-xs-4'>";
		foreach ($extras as $extra) {
			echo "<p><strong>".$extra->getName()." : </strong>".$extra->getContent()."</p>";
		}
		echo "</div>";
	}

	?>


	<?php
	if(count($relatedAccessories)>0) {
		
		echo "<div class='col-md-6'><hr />";
		echo "<h4>Accessoires</h4>";
		foreach ($relatedAccessories as $subProduct) {
			 $detailLink = $this->url(array(
	            "id" => $subProduct->getId(),
	            "text" => $subProduct->getName(),
	            "prefix" => $this->document->getFullPath()
	        ), "produits");
			echo "<a href=\"".$detailLink."\">".$subProduct->getName()."-".$subProduct->getCode()."</a><br />";
		}
		echo "</div>";
	}

	if(count($relatedProducts)>0) {
		
			echo "<div class='col-md-6'>whr />";
			echo "<h4>Produits associés</h4>";
		foreach ($relatedProducts as $subProduct) {
			 $detailLink = $this->url(array(
	            "id" => $subProduct->getId(),
	            "text" => $subProduct->getName(),
	            "prefix" => $this->document->getFullPath()
	        ), "produits");
			echo "<a href=\"".$detailLink."\">".$subProduct->getName()."-".$subProduct->getCode()."</a><br />";
		}
		echo "</div>";
	}


	?>
</div>



	

	<?php 
	if(count($associatedArticles)>0) {
		echo '<div class="row">';
		//echo "<h3>Articles associés</h3>";
		
		foreach ($associatedArticles as $article) {
			echo "<div class='col-md-4'><hr /><h3>".$article->getName()."</h3>";
			echo $article->getContent();
			$associatedDocuments = $article->getDocuments();
			foreach ($associatedDocuments as $document) {
				$linkLabel = strlen($document->getProperty("downloadLink"))>0?$document->getProperty("downloadLink"):"Télécharger";
				echo '<a href="'.$document->getFullPath().'" target="_blank">> '.$linkLabel.'</a><br />';
					
			}
			echo "</div>";
		}
		echo "</div>";
	}
	?>

<!-- Second col / -->
</div>
</div>
<!-- FIN MAIN LAYOUT / -->


