<?php 

return [
    1 => [
        "name" => "Left Navigation Start Node",
        "description" => "Where the tree of the left navigation should start",
        "key" => "leftNavStartNode",
        "type" => "document",
        "data" => "",
        "config" => "",
        "ctype" => "document",
        "inheritable" => 1,
        "creationDate" => 0,
        "modificationDate" => 0,
        "id" => 1
    ],
    2 => [
        "name" => "Hide Left Navigation",
        "description" => "",
        "key" => "leftNavHide",
        "type" => "bool",
        "data" => "true",
        "config" => "",
        "ctype" => "document",
        "inheritable" => 0,
        "creationDate" => 0,
        "modificationDate" => 0,
        "id" => 2
    ],
    3 => [
        "name" => "Header Color",
        "description" => "",
        "key" => "headerColor",
        "type" => "select",
        "data" => "",
        "config" => "orange,blue,green",
        "ctype" => "document",
        "inheritable" => 1,
        "creationDate" => 0,
        "modificationDate" => 0,
        "id" => 3
    ],
    4 => [
        "name" => "Sidebar",
        "description" => "",
        "key" => "sidebar",
        "type" => "document",
        "data" => "",
        "config" => "",
        "ctype" => "document",
        "inheritable" => 1,
        "creationDate" => 0,
        "modificationDate" => 0,
        "id" => 4
    ],
    5 => [
        "name" => "downloadLink",
        "description" => "",
        "key" => "downloadLink",
        "type" => "text",
        "data" => "",
        "config" => NULL,
        "ctype" => "asset",
        "inheritable" => 0,
        "creationDate" => 1386687364,
        "modificationDate" => 1386687393,
        "id" => 5
    ],
    6 => [
        "name" => "product",
        "description" => "",
        "key" => "product",
        "type" => "object",
        "data" => NULL,
        "config" => "",
        "ctype" => "asset",
        "inheritable" => 1,
        "creationDate" => 1398328130,
        "modificationDate" => 1398328283,
        "id" => 6
    ],
    7 => [
        "id" => 7,
        "name" => "Réalisation Title",
        "description" => "Titre de la réalisation",
        "key" => "realisation_title",
        "type" => "text",
        "data" => NULL,
        "config" => NULL,
        "ctype" => "asset",
        "inheritable" => TRUE,
        "creationDate" => 1450196248,
        "modificationDate" => 1477043511
    ],
    8 => [
        "id" => 8,
        "name" => "Réalisation description",
        "description" => "Description de la réalisation",
        "key" => "realisation_description",
        "type" => "text",
        "data" => "",
        "config" => NULL,
        "ctype" => "asset",
        "inheritable" => TRUE,
        "creationDate" => 1477043516,
        "modificationDate" => 1477044502
    ],
    9 => [
        "id" => 9,
        "name" => "Réalisation teinte",
        "description" => "Réalisation Teinte LPN",
        "key" => "realisation_teinte",
        "type" => "object",
        "data" => "",
        "config" => "",
        "ctype" => "asset",
        "inheritable" => TRUE,
        "creationDate" => 1477043581,
        "modificationDate" => 1477044466
    ],
    10 => [
        "id" => 10,
        "name" => "Copyright",
        "description" => "",
        "key" => "copyright",
        "type" => "text",
        "data" => "",
        "config" => NULL,
        "ctype" => "asset",
        "inheritable" => TRUE,
        "creationDate" => 1481729391,
        "modificationDate" => 1481729469
    ]
];
